apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
  labels:
    {{- include "otus-users.labels" . | nindent 4 }}
type: Opaque
data:
  user: postgres
  password: postgres
  postgres-password: postgres